In [183]:
println("Hello Julia!!!")

Hello Julia!!!


In [184]:
x = 5
y =7

7

In [185]:
x*y

35

In [186]:
x/y

0.7142857142857143

In [187]:
x+y

12

In [188]:
x^y # Power

78125

In [189]:
a = "Jai"
b = "Shree Ram"

"Shree Ram"

In [190]:
a * b

"JaiShree Ram"

In [191]:
a * " " * b # Perfect Sweet

"Jai Shree Ram"

In [192]:
typeof(a)

String

In [193]:
typeof(x)

Int64

In [194]:
typeof(7.0)

Float64

In [195]:
?cos # Calling Help Function.

search: cos cosh cosd cosc cospi acos acosh acosd sincos sincosd sincospi const



```
cos(x)
```

Compute cosine of `x`, where `x` is in radians.

---

```
cos(A::AbstractMatrix)
```

Compute the matrix cosine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the cosine. Otherwise, the cosine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> cos(fill(1.0, (2,2)))
2×2 Matrix{Float64}:
  0.291927  -0.708073
 -0.708073   0.291927
```


In [196]:
?sin

search: sin sinh sind sinc sinpi sincos sincosd sincospi asin using isinf asinh



```
sin(x)
```

Compute sine of `x`, where `x` is in radians.

---

```
sin(A::AbstractMatrix)
```

Compute the matrix sine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the sine. Otherwise, the sine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> sin(fill(1.0, (2,2)))
2×2 Matrix{Float64}:
 0.454649  0.454649
 0.454649  0.454649
```


In [197]:
?print

search: print println printstyled sprint isprint prevind parentindices precision



```
print([io::IO], xs...)
```

Write to `io` (or to the default output stream [`stdout`](@ref) if `io` is not given) a canonical (un-decorated) text representation. The representation used by `print` includes minimal formatting and tries to avoid Julia-specific details.

`print` falls back to calling `show`, so most types should just define `show`. Define `print` if your type has a separate "plain" representation. For example, `show` displays strings with quotes, and `print` displays strings without quotes.

[`string`](@ref) returns the output of `print` as a string.

# Examples

```jldoctest
julia> print("Hello World!")
Hello World!
julia> io = IOBuffer();

julia> print(io, "Hello", ' ', :World!)

julia> String(take!(io))
"Hello World!"
```


In [198]:
arr = [] # The index starts from 1,2....n

Any[]

In [199]:
push!(arr,1,2,3,4) # Here push! is used to add in the elements in the array.

4-element Vector{Any}:
 1
 2
 3
 4

In [200]:
# i can also play with it like this
arr[2] = 9

9

In [201]:
arr # The second element is replaced by 9

4-element Vector{Any}:
 1
 9
 3
 4

In [202]:
push!(arr,"Jai Shree Hanuman") # we can also enter the string elements as well.

5-element Vector{Any}:
 1
 9
 3
 4
  "Jai Shree Hanuman"

In [203]:
# let's try append function with some new empty array
arr1 = []

Any[]

In [204]:
push!(arr1,"Hello Dhruv")

1-element Vector{Any}:
 "Hello Dhruv"

In [205]:
append!(arr1,"How you doin!") # segretated and then added as individual elements in the array.

14-element Vector{Any}:
 "Hello Dhruv"
 'H': ASCII/Unicode U+0048 (category Lu: Letter, uppercase)
 'o': ASCII/Unicode U+006F (category Ll: Letter, lowercase)
 'w': ASCII/Unicode U+0077 (category Ll: Letter, lowercase)
 ' ': ASCII/Unicode U+0020 (category Zs: Separator, space)
 'y': ASCII/Unicode U+0079 (category Ll: Letter, lowercase)
 'o': ASCII/Unicode U+006F (category Ll: Letter, lowercase)
 'u': ASCII/Unicode U+0075 (category Ll: Letter, lowercase)
 ' ': ASCII/Unicode U+0020 (category Zs: Separator, space)
 'd': ASCII/Unicode U+0064 (category Ll: Letter, lowercase)
 'o': ASCII/Unicode U+006F (category Ll: Letter, lowercase)
 'i': ASCII/Unicode U+0069 (category Ll: Letter, lowercase)
 'n': ASCII/Unicode U+006E (category Ll: Letter, lowercase)
 '!': ASCII/Unicode U+0021 (category Po: Punctuation, other)

In [206]:
arr2 = []

Any[]

In [207]:
append!(arr2,[1,2,3,4,5]) # this is just 2nd way of adding elements to the array.

5-element Vector{Any}:
 1
 2
 3
 4
 5

In [208]:
# now we will define a special kind of array in which in which only integer values can be taken
f = Array{Int}(undef,1)

1-element Vector{Int64}:
 1

In [209]:
f[1] = 7

7

In [210]:
f

1-element Vector{Int64}:
 7

In [211]:
push!(f,7,4,5,5,1)

6-element Vector{Int64}:
 7
 7
 4
 5
 5
 1

In [212]:
push!(f, "Hello") # it gives error as f can only take integral values. here string is given

LoadError: MethodError: Cannot `convert` an object of type String to an object of type Int64
Closest candidates are:
  convert(::Type{T}, ::Ptr) where T<:Integer at pointer.jl:23
  convert(::Type{T}, ::T) where T<:Number at number.jl:6
  convert(::Type{T}, ::Number) where T<:Number at number.jl:7
  ...

In [213]:
push!(f, 7.3) # it gives error as f can only take integral values. here float is given

LoadError: InexactError: Int64(7.3)

In [214]:
g = Array{AbstractFloat}(undef,1) # it will convert integral value to float and the use it.

1-element Vector{AbstractFloat}:
 #undef

In [215]:
push!(g,7.3)

2-element Vector{AbstractFloat}:
 #undef
   7.3

In [216]:
push!(g,9) 

3-element Vector{AbstractFloat}:
 #undef
   7.3
   9.0

In [217]:
h = Array{Real}(undef,1)

1-element Vector{Real}:
 #undef

In [218]:
h[1] = 7.37

7.37

In [219]:
h

1-element Vector{Real}:
 7.37

In [220]:
push!(h,1,2,3.3,4.9,5)

6-element Vector{Real}:
 7.37
 1
 2
 3.3
 4.9
 5

In [221]:
j = Array{Float64}(undef,3,9)

3×9 Matrix{Float64}:
 2.40957e-314  2.40957e-314  2.40957e-314  …  2.40957e-314  2.40957e-314
 2.40957e-314  2.41028e-314  2.40957e-314     2.40957e-314  2.40957e-314
 2.40957e-314  2.40957e-314  2.40957e-314     2.40957e-314  2.40957e-314

In [222]:
j[2,1] = 0

0

In [224]:
j # the manupulation do work

3×9 Matrix{Float64}:
 2.40957e-314  2.40957e-314  2.40957e-314  …  2.40957e-314  2.40957e-314
 0.0           2.41028e-314  2.40957e-314     2.40957e-314  2.40957e-314
 2.40957e-314  2.40957e-314  2.40957e-314     2.40957e-314  2.40957e-314

In [225]:
# Let's create some Fundamental Arrays
k = zeros(3,3)

3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [226]:
l = ones(4,5)

4×5 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0