In [1]:
z = zeros(10)
l = []

Any[]

In [2]:
z

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [8]:
r = range(1,20,length=70) # take 70 enteries between (1,20)

1.0:0.2753623188405797:20.0

In [9]:
0.2753623188405797 * 70

19.27536231884058

In [12]:
typeof(r)

StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}

In [15]:
size(r)

(70,)

In [10]:
u = 1:2:20 # it is going from 1 to 19 with 10 elements

1:2:19

In [11]:
typeof(u)

StepRange{Int64, Int64}

In [14]:
size(u)

(10,)

In [16]:
c = range(1,19,length=10) # Equivalent of u

1.0:2.0:19.0

In [17]:
z = zeros(3,4)

3×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [18]:
size(z)

(3, 4)

In [19]:
l1 = [x for x in 1:20] # x lies between 1,20

20-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20

In [20]:
l2 = [x%2 for x in 1:20] # It gives out the reminder for each term in array on division with 2

20-element Vector{Int64}:
 1
 0
 1
 0
 1
 0
 1
 0
 1
 0
 1
 0
 1
 0
 1
 0
 1
 0
 1
 0

In [21]:
display(z) # Another way of calling it

3×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0